version: "3.7"
services:
    hadoop-master:
        image: hadoop:1.1
        container_name: hadoop-master
        hostname: master
        ports:
            - "8088:8088"
            - "9870:9870"
        networks:
            hadoop-network:
                ipv4_address: 192.168.123.100
        # links:
        #     - hadoop-worker-1
        command: bash -c 'while true; do sleep 1; done'

    # hadoop-worker-1:
    #     image: hadoop:1.1
    #     container_name: hadoop-worker-1
    #     hostname: worker01
    #     networks: 
    #         hadoop-network:
    #             ipv4_address: 192.168.123.101
    #     command: bash -c 'while true; do sleep 1; done'

networks:
    hadoop-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.123.0/24
